### PR TITLE
Added ability to change the region

### PR DESCRIPTION
**Pull request by teu**
Adding one variable, added the ability to move between aws regions

### CODE REVIEW

**Comment by tverbiscer** [comment]
@teu Awesome, thanks for the pull request.  I'll look at it shortly.

**Comment by teu** [comment]
Just a reminder ;-)

**Comment by teu** [comment]
Hi, can you please integrate the change? I'd like to deploy this on more machines

**Comment by teu** [comment]
Any movement on this?

**Comment by tverbiscer** [comment]
Sorry about the delay, thanks again for the PR.

**Comment by teu** [comment]
Hi, is there a change this will ever be merged? 
Thanks

**Comment by teu** [comment]
Hi, is this repo abbandoned?

**Pull request closed without merging**
